# -*- coding: utf-8 -*-
"""Auto-generated by scripts/build_mschema.py — do not edit by hand."""

MSCHEMA = r'''【DB_ID】 fahmai   (Postgres grading DB — schemas fah_sai_lpk_model + fah_sai_lpk_core)
# Prefer the 360/event/catalog views (fah_sai_lpk_model) over raw fact_* tables.
# fah_sai_lpk_mart views (v_sales_line, v_sales_order, v_vendor_payment, …) also exist
# but are NOT on the search_path — qualify with schema or use the model views instead.

# Table: sales_order_360  (1 row/txn; basket_total/discount/net in _thb; no fiscal_year_ce — derive from business_event_date)
[
  (source_table:TEXT, ex:[FACT_SALES])
  (source_pk:TEXT, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (source_aliases:ARRAY, ex:[['FACT_SALES', 'DIM_BRANCH', 'DIM_CUSTOM…])
  (txn_id:TEXT, PK, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (branch_code:TEXT, -> dim_branch.branch_code, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (branch_name_en:TEXT, ex:[FahMai Phuket Road, FahMai Chiang Mai Maya, FahMai Pattaya Central])
  (branch_type:TEXT, ex:[hq, branch, remote])
  (is_service_center:BOOL, ex:[False, True])
  (customer_id:TEXT, -> dim_customer.customer_id, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000003])
  (customer_type:TEXT, ex:[B2C, B2B])
  (b2b_subtype:TEXT, ex:[Enterprise, SME])
  (customer_payment_terms:TEXT, ex:[NET-30, NET-60])
  (loyalty_tier:TEXT, ex:[silver, none, gold])
  (customer_province:TEXT, ex:[Bangkok])
  (customer_region:TEXT, ex:[BKK])
  (account_manager_id:TEXT, ex:[EMP-L3-00002])
  (employee_id:TEXT, -> dim_employee.employee_id, ex:[EMP-L3-00002, EMP-L3-00011])
  (sales_employee_position:TEXT, ex:[B2B Account Manager, Cashier])
  (sales_employee_position_level:TEXT, ex:[Manager, IC])
  (sales_employee_dept_code:TEXT, ex:[B2B, RET])
  (channel:TEXT, ex:[offline, b2b, online])
  (basket_total_thb:NUMERIC(18,2), ex:[239600.00, 379900.00, 298200.00])
  (discount_total_thb:NUMERIC(18,2), ex:[5364.00, 40092.00, 4932.00])
  (net_total_thb:NUMERIC(18,2), ex:[239600.00, 379900.00, 20640.00])
  (shipping_charge_thb:NUMERIC(18,2), ex:[0.00])
  (shipping_method:TEXT, ex:[enterprise_fleet, express, standard])
  (promo_campaign_id:TEXT, -> dim_promo_campaign.campaign_id, ex:[CLEAR-EOY-2567, CLEAR-EOY-2568, MEGA-1111-2567])
  (promo_description_en:TEXT)
  (promo_start_timestamp:TIMESTAMP, ex:[2025-11-09 17:00:00+00:00, 2025-12-10 17:00:00+00:00, 2024-11-10 17:00:00+00:00])
  (promo_end_timestamp:TIMESTAMP, ex:[2025-12-31 16:59:59+00:00, 2024-12-31 16:59:59+00:00, 2025-12-13 16:59:59+00:00])
  (payment_method:TEXT, ex:[bank_transfer, cash, credit_card])
  (payment_status:TEXT, ex:[pending, paid])
  (payment_due_date:DATE, ex:[2025-07-31, 2025-02-18, 2026-01-13])
  (payment_received_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (settlement_bank_txn_id:TEXT, ex:[BT-202401-1040227460347, BT-202401-157159523436, BT-202401-248898262592])
  (settlement_account_id:TEXT, ex:[KBANK-OPER])
  (settlement_transaction_type:TEXT, ex:[deposit])
  (settlement_amount_thb:NUMERIC(18,2), ex:[239600.00, 379900.00, 226000.00])
  (web_log_line_id:TEXT, ex:[web_20250422.jsonl:line18, web_20240705.jsonl:line6, web_20250306.jsonl:line84])
  (schema_version:TEXT, ex:[2, 1])
  (is_b2b:BOOL, ex:[False, True])
  (retry_idempotency_marker:TEXT)
]

# Table: sales_line_360  (line items; join to sales_order_360 on txn_id)
[
  (source_table:TEXT, ex:[FACT_SALES_LINE_ITEM])
  (source_pk:TEXT, ex:[1000001286164, 1000001591146, 10000045503])
  (source_aliases:ARRAY, ex:[['FACT_SALES_LINE_ITEM', 'FACT_SALES', '…])
  (line_item_id:TEXT, PK, ex:[1000001286164, 1000001591146, 10000045503])
  (txn_id:TEXT, -> sales_order_360.txn_id, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (branch_code:TEXT, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (customer_id:TEXT, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000003])
  (employee_id:TEXT, ex:[EMP-L3-00002, EMP-L3-00011])
  (channel:TEXT, ex:[b2b, offline, online])
  (payment_method:TEXT, ex:[bank_transfer, cash, credit_card])
  (payment_status:TEXT, ex:[paid, pending])
  (is_b2b:BOOL, ex:[False, True])
  (order_net_total_thb:NUMERIC(18,2), ex:[3920.00, 4018.00, 4130.00])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[AW-MN-001, DN-LT-010, NT-LT-001])
  (brand_family:TEXT, ex:[ArcWave, Dawn, FahMai])
  (dept_code:TEXT, ex:[SF])
  (dept_name_en:TEXT, ex:[SaiFah Division])
  (category:TEXT, ex:[laptop, monitor, smartphone])
  (subcategory:TEXT, ex:[flagship, midrange])
  (msrp_thb:NUMERIC(18,2), ex:[4900.00, 5900.00, 6900.00])
  (msrp_tier:TEXT, ex:[10K-30K, <10K, >=30K])
  (is_third_party:BOOL, ex:[False, True])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-001, V-002])
  (vendor_name_en:TEXT, ex:[NovaTech, NovaTech Service])
  (launch_date:DATE, ex:[2023-01-01, 2024-01-01, 2025-07-15])
  (end_of_life_date:DATE)
  (warranty_months:INT, ex:[12, 24, 36])
  (care_plus_eligible:BOOL, ex:[False, True])
  (quantity:INT, ex:[1])
  (unit_price_thb:NUMERIC(18,2), ex:[4900.00, 5900.00, 6900.00])
  (line_discount_thb:NUMERIC(18,2), ex:[0.00])
  (line_total_thb:NUMERIC(18,2), ex:[4900.00, 5900.00, 6900.00])
  (is_care_plus:BOOL, ex:[False])
  (pos_log_line_id:TEXT, ex:[pos_KKC-CTRL_20250922.tsv:line15, pos_BKK-CTW_20240130.tsv:line7, pos_BKK-R9_20241023.tsv:line18])
]

# Table: finance_event  (UNION bank_txns+refunds+vendor_payments+payroll; event_type discriminates; amount_direction: credit/debit)
[
  (source_table:TEXT, ex:[FACT_BANK_TRANSACTION, FACT_PAYROLL, FACT_REFUND_PAID])
  (source_pk:TEXT, ex:[1000243805828, 1000357467770, 1000373797515])
  (source_aliases:ARRAY, ex:[['FACT_BANK_TRANSACTION', 'DIM_BANK_ACCO…, ['FACT_PAYROLL', 'DIM_EMPLOYEE', 'DIM_BR…, ['FACT_REFUND_PAID', 'FACT_RETURN', 'FAC…])
  (event_type:TEXT, ex:[bank_transaction, payroll, refund_paid])
  (event_id:TEXT, PK, ex:[1000243805828, 1000357467770, 1000373797515])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (bank_txn_id:TEXT, ex:[BT-202401-1001612189611, BT-202401-1001773818030, BT-202401-100288086373])
  (account_id:TEXT, -> dim_bank_account.account_id, ex:[BBL-OPER, KBANK-OPER, OPER-BKK-CTW])
  (bank:TEXT, ex:[BBL, KBank, SCB])
  (account_role:TEXT, ex:[operating])
  (associated_branch_code:TEXT, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (transaction_type:TEXT, ex:[deposit, fee, transfer])
  (related_entity_table:TEXT, ex:[DIM_EMPLOYEE, DIM_VENDOR, FACT_LOYALTY_LEDGER])
  (related_entity_id:TEXT, ex:[1000243805828, 100024549842, 1000357467770])
  (amount_thb:NUMERIC(18,2), ex:[-500000.00, -350000.00, -300000.00])
  (amount_direction:TEXT, ex:[inflow, outflow])
  (balance_after_thb:NUMERIC(18,2), ex:[-20658100.00, -20628200.00, -20589050.00])
  (counterparty:TEXT, ex:[BBL-OPER, CUST-L3-000004, CUST-L3-000005])
  (description:TEXT)
  (customer_id:TEXT, ex:[CUST-L3-011021, CUST-L3-013470, CUST-L3-028184])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-006, V-001, V-002])
  (vendor_name_en:TEXT, ex:[VeloShip, PayWise, NovaTech])
  (employee_id:TEXT, -> dim_employee.employee_id, ex:[EMP-L3-00007, EMP-L3-00393, EMP-L3-00148])
  (employee_position_level:TEXT, ex:[Director, Manager, C-level])
  (refund_id:TEXT, ex:[RFD-202508-13011745, RFD-202506-09024674, RFD-202506-12024952])
  (return_id:TEXT, ex:[RET-202510-12017872, RET-202412-30022643, RET-202404-04000173])
  (payment_id:TEXT, ex:[VP-202509-817251, VP-202504-4671869, VP-202406-14314083])
  (payroll_id:TEXT, ex:[511708253693, 816637459373, 799478610278])
  (vendor_invoice_id:TEXT, ex:[V-001-INV-2567-769224, V-014-INV-2567-601322, V-006-INV-2567-547649])
  (invoice_period_start:DATE, ex:[2025-03-11, 2024-07-01, 2025-12-01])
  (invoice_period_end:DATE, ex:[2025-03-11, 2024-02-29, 2025-03-31])
  (request_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (approver_employee_id:TEXT, -> dim_employee.employee_id, ex:[EMP-L3-00008, EMP-L3-00005, EMP-L3-00010])
  (cosig_employee_id:TEXT, ex:[EMP-L3-00001])
  (attributes:JSONB)
]

# Table: customer_ops_event  (UNION returns+refunds+warranty+cs+shipping+loyalty+promo; event_type discriminates)
[
  (source_table:TEXT, ex:[FACT_CS_INTERACTION, FACT_LOYALTY_LEDGER, FACT_PROMO_REDEMPTION])
  (source_pk:TEXT, ex:[1000026317711, 1000052950198, 100005633475])
  (source_aliases:ARRAY, ex:[['FACT_CS_INTERACTION', 'DIM_CUSTOMER', …, ['FACT_LOYALTY_LEDGER', 'FACT_SALES', 'D…, ['FACT_PROMO_REDEMPTION', 'FACT_SALES', …])
  (event_type:TEXT, ex:[cs_interaction, loyalty_ledger, promo_redemption])
  (event_id:TEXT, PK, ex:[1000026317711, 1000052950198, 100005633475])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (customer_id:TEXT, -> dim_customer.customer_id, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000004])
  (customer_type:TEXT, ex:[B2B, B2C])
  (loyalty_tier:TEXT, ex:[gold, none, platinum])
  (employee_id:TEXT, ex:[EMP-L3-00005, EMP-L3-00010, EMP-L3-00019])
  (employee_position_level:TEXT, ex:[IC, Manager])
  (branch_code:TEXT, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (branch_name_en:TEXT, ex:[Bangkok Ratchada 9 HQ, FahMai Central World, FahMai Chiang Mai Maya])
  (txn_id:TEXT, -> sales_order_360.txn_id, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (line_item_id:TEXT, ex:[934129273956, 310616972004, 663010055850])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-074])
  (brand_family:TEXT, ex:[SaiFah, Dawn, ArcWave])
  (category:TEXT, ex:[laptop, monitor, smartphone])
  (subcategory:TEXT, ex:[midrange, flagship])
  (vendor_id:TEXT, ex:[V-001, V-002])
  (shipping_vendor_id:TEXT, ex:[V-006])
  (shipping_vendor_name_en:TEXT, ex:[VeloShip])
  (amount_thb:NUMERIC(18,2), ex:[5364.00, 4932.00, 10320.00])
  (points_delta:INT, ex:[-1209, 1489, -1786])
  (resulting_balance_points:INT, ex:[1489, 4790, 273])
  (resulting_tier:TEXT, ex:[platinum, none, gold])
  (return_id:TEXT, ex:[RET-202510-12017872, RET-202412-30022643, RET-202404-04000173])
  (refund_id:TEXT, ex:[RFD-202508-13011745, RFD-202506-09024674, RFD-202506-12024952])
  (warranty_claim_id:TEXT, ex:[WC-202508-18020754, WC-202409-22003292, WC-202409-21012949])
  (shipping_id:TEXT, ex:[1013251693941, 459904380594, 790070558102])
  (cs_interaction_id:TEXT, ex:[CSI-202512-9158100, CSI-202504-2111470, CSI-202505-2026965])
  (loyalty_ledger_id:TEXT, ex:[59142192913, 3503124749, 1068766876409])
  (promo_redemption_id:TEXT, ex:[1019597839275, 94666346226, 525891077361])
  (campaign_id:TEXT, -> dim_promo_campaign.campaign_id, ex:[MEGA-1111-2567, MEGA-1111-2568, CLEAR-EOY-2568])
  (channel:TEXT, ex:[line_oa, online, offline])
  (interaction_type:TEXT, ex:[chat_general, refund_request, warranty_claim])
  (resolution_type:TEXT, ex:[open, approved, pending])
  (return_reason:TEXT, ex:[vendor recall — V-002 NovaTech battery, hardware batch defect — WK-SW-004 Watch …, customer_change_of_mind])
  (claim_reason:TEXT, ex:[vendor batch defect (V-004-MON-BATCH-256…, battery swelling concern — NT-LT-001 (pr…, defect])
  (routing_destination:TEXT, ex:[novatech_service, fahmai_cs])
  (shipping_confirmation_status:TEXT, ex:[shipped])
  (loyalty_event_type:TEXT, ex:[expired, tier_change, redeemed])
  (discount_applied_thb:NUMERIC(18,2), ex:[5364.00, 4932.00, 10320.00])
  (attributes:JSONB)
]

# Table: inventory_event  (UNION movements+monthly_snapshots; event_type discriminates; closing_units from snapshots)
[
  (source_table:TEXT, ex:[FACT_INVENTORY_MONTHLY_SNAPSHOT, FACT_INVENTORY_MOVEMENT])
  (source_pk:TEXT, ex:[1, 10, 100])
  (source_aliases:ARRAY, ex:[['FACT_INVENTORY_MONTHLY_SNAPSHOT', 'DIM…, ['FACT_INVENTORY_MOVEMENT', 'DIM_PRODUCT…])
  (event_type:TEXT, ex:[inventory_monthly_snapshot, inventory_movement])
  (event_id:TEXT, PK, ex:[1, 10, 100])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (month_end_date:DATE, ex:[2024-02-29, 2025-03-31, 2024-10-31])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[AW-MN-001, DN-LT-010, NT-LT-001])
  (brand_family:TEXT, ex:[ArcWave, Dawn, FahMai])
  (dept_code:TEXT, ex:[SF])
  (dept_name_en:TEXT, ex:[SaiFah Division])
  (category:TEXT, ex:[laptop, monitor, smartphone])
  (subcategory:TEXT, ex:[flagship, midrange])
  (vendor_id:TEXT, ex:[V-001, V-002])
  (vendor_name_en:TEXT, ex:[NovaTech, NovaTech Service])
  (branch_code:TEXT, -> dim_branch.branch_code, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (branch_name_en:TEXT, ex:[Bangkok Ratchada 9 HQ, FahMai Central World, FahMai Chiang Mai Maya])
  (branch_type:TEXT, ex:[branch, hq, remote])
  (movement_type:TEXT, ex:[opening_balance, sale, transfer_in])
  (quantity:INT, ex:[-50, -1, 50])
  (related_txn_id:TEXT, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (closing_units:INT, ex:[652, 273, 51])
  (is_stockout:BOOL, ex:[False, True])
  (attributes:JSONB)
]

# Table: policy_catalog  (UNION policy_version+promo+vendor_contract+signing_ladder; effective_date/end_date as-of filter applies)
[
  (source_table:TEXT, ex:[DIM_VENDOR_CONTRACT_VERSION, dim_promo_mechanic, dim_signing_authority_ladder])
  (source_pk:TEXT, ex:[1, 10, 11])
  (source_aliases:ARRAY, ex:[['DIM_VENDOR_CONTRACT_VERSION', 'DIM_VEN…, ['DIM_POLICY_VERSION'], ['dim_signing_authority_ladder', 'DIM_PO…])
  (policy_domain:TEXT, ex:[vendor_contract_version, promo_mechanic, policy_version])
  (catalog_row_id:TEXT, ex:[1, 10, 11])
  (policy_class:TEXT, ex:[membership, promotion, refund])
  (policy_variable:TEXT, ex:[warranty_routing, mechanic, return_window_days])
  (scope_filter:TEXT, ex:[consumer_brand, logistics, payments])
  (value_numeric:NUMERIC, ex:[0.3000, 0.0100, 0.1500])
  (value_text:TEXT, ex:[Price update, Termination amendment, Peak-season surcharge])
  (effective_date:DATE, ex:[2025-11-09, 2024-07-01, 2025-12-01])
  (end_date:DATE, ex:[2025-11-12, 2025-03-31, 2024-07-01])
  (start_timestamp:TIMESTAMP, ex:[2025-11-09 17:00:00+00:00, 2025-12-10 17:00:00+00:00, 2024-11-10 17:00:00+00:00])
  (end_timestamp:TIMESTAMP, ex:[2025-12-31 16:59:59+00:00, 2024-12-31 16:59:59+00:00, 2025-12-13 16:59:59+00:00])
  (campaign_id:TEXT, ex:[CLEAR-EOY-2567, CLEAR-EOY-2568, MEGA-1111-2567])
  (promo_mechanic_id:TEXT, ex:[1, 4, 8])
  (vendor_id:TEXT, ex:[V-001, V-002, V-014])
  (vendor_name_en:TEXT, ex:[PayWise, NorthernShip, LegacyShip])
  (vendor_contract_version_id:TEXT, ex:[1, 9, 4])
  (contract_version_number:INT, ex:[4, 3, 1])
  (position_level_code:TEXT, ex:[Director, C-level, Manager])
  (dept_code:TEXT, ex:[SUP])
  (amount_ceiling_thb:NUMERIC(18,2), ex:[5000000.00, 5000.00, 100000.00])
  (min_co_signers:INT, ex:[0, 1])
  (co_signer_min_position_level_code:TEXT, ex:[Manager])
  (document_filename:TEXT, ex:[contracts/V-006-v1.pdf, contracts/V-001-v4.pdf, contracts/V-014-v3.pdf])
  (description_th:TEXT)
  (description_en:TEXT)
  (attributes:JSONB)
]

# Table: product_catalog  (dim_product enriched with vendor name, care_plus tiers, recall history)
[
  (source_table:TEXT, ex:[DIM_PRODUCT])
  (source_pk:TEXT, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (source_aliases:ARRAY, ex:[['DIM_PRODUCT', 'DIM_DEPARTMENT', 'DIM_V…])
  (sku_id:TEXT, PK, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (brand_family:TEXT, ex:[Dawn, NovaTech, ArcWave])
  (dept_code:TEXT, ex:[SF])
  (dept_name_en:TEXT, ex:[SaiFah Division])
  (dept_type:TEXT, ex:[product_division])
  (category:TEXT, ex:[smartwatch, laptop, monitor])
  (subcategory:TEXT, ex:[flagship, midrange])
  (msrp_thb:NUMERIC(18,2), ex:[6900.00, 4900.00, 29900.00])
  (msrp_tier:TEXT, ex:[>=30K, <10K, 10K-30K])
  (is_third_party:BOOL, ex:[False, True])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-001, V-002])
  (vendor_name_en:TEXT, ex:[NovaTech Service, NovaTech])
  (vendor_category:TEXT, ex:[consumer_brand])
  (vendor_role:TEXT, ex:[partner_brand, warranty_partner])
  (launch_date:DATE, ex:[2023-01-01, 2024-01-01, 2025-07-15])
  (end_of_life_date:DATE)
  (warranty_months:INT, ex:[12, 36, 24])
  (care_plus_eligible:BOOL, ex:[False, True])
  (care_plus_tier_count:INT, ex:[0, 1])
  (min_care_plus_price_thb:NUMERIC(18,2), ex:[3490.00, 3990.00])
  (max_care_plus_price_thb:NUMERIC(18,2), ex:[3490.00, 3990.00])
  (max_care_plus_coverage_months:INT, ex:[24, 36])
  (recall_history_count:INT, ex:[0, 3])
  (latest_recall_status:TEXT, ex:[completed])
  (latest_recall_transition_date:DATE, ex:[2025-10-15])
  (care_plus_tiers:JSONB, ex:[[], [{'tier_row_id': '2', 'sku_category': No…, [{'tier_row_id': '1', 'sku_category': No…])
  (recall_history:JSONB)
]

# Table: document_evidence  (RAG/doc chunks; source_kind e.g. 'doc_chat_line_oa'; for chat/doc counts+keywords use SQL here)
[
  (evidence_row_id:TEXT, ex:[child_0365a33f85b1e4e276959e80, child_bcf445a9994180618bdeb53c, child_8c564e3901b5609cd530d029])
  (source_table:TEXT, ex:[DIM_PRODUCT, DIM_BRANCH, DIM_EMPLOYEE])
  (source_pk:TEXT, ex:[CUST-L3-B2B-023600, CUST-L3-B2B-028100, CUST-L3-B2B-022300])
  (source_aliases:ARRAY, ex:[['fah_sai_lpk_rag.source_documents', 'fa…])
  (retrieval_profile:TEXT, ex:[bge_m3_v1])
  (chunk_id:TEXT, PK, ex:[child_0000951d5a16d7d040dd9be0, child_00018daed43f26a1115d70c6, child_0002f655aa5d792263772dac])
  (child_chunk_id:TEXT, ex:[child_0000951d5a16d7d040dd9be0, child_00018daed43f26a1115d70c6, child_0002f655aa5d792263772dac])
  (parent_chunk_id:TEXT, ex:[chunk_000065cee549b3957c9d8f96, chunk_000117f62612b702c78f9611, chunk_0002b2031f34f7987286fd8f])
  (source_document_id:TEXT, ex:[doc_00009b75097e7c79e9afaa3e, doc_0001e3470c9001778ede395e, doc_0002da3c6ff2af1b8cf2673f])
  (source_path:TEXT, ex:[super-ai-engineer-season-6-fah-mai-the-f…, super-ai-engineer-season-6-fah-mai-the-f…, super-ai-engineer-season-6-fah-mai-the-f…])
  (source_kind:TEXT, ex:[doc_DOCS_ANOMALY_INSIGHTS.md, doc_L1_KB_CONSISTENCY_RISK.md, doc_LOA_EVENT_INSIGHTS.md])
  (artifact_id:TEXT)
  (doc_id:TEXT)
  (chunk_index:INT, ex:[0, 1, 2])
  (chunk_text:TEXT)
  (parent_text:TEXT, ex:[[source=super-ai-engineer-season-6-fah-m…, [source=super-ai-engineer-season-6-fah-m…, [source=super-ai-engineer-season-6-fah-m…])
  (token_count:INT, ex:[9, 10, 14])
  (search_tsv:TSVECTOR)
  (embedding_model:TEXT, ex:[BAAI/bge-m3])
  (has_embedding:BOOL, ex:[True])
  (document_source_table:TEXT)
  (document_source_pk:TEXT)
  (entity_link_id:INT, ex:[16592, 16204, 16806])
  (entity_type:TEXT, ex:[sku, branch, employee])
  (entity_id:TEXT, ex:[CUST-L3-B2B-023600, CUST-L3-B2B-028100, CUST-L3-B2B-022300])
  (linked_table:TEXT, ex:[DIM_PRODUCT, DIM_BRANCH, DIM_CUSTOMER])
  (linked_column:TEXT, ex:[employee_id, customer_id, sku_id])
  (link_method:TEXT, ex:[exact_id])
  (confidence:NUMERIC(5,4), ex:[1.0000])
  (chunk_metadata:JSONB)
  (parent_metadata:JSONB)
  (source_metadata:JSONB)
]

# Table: dim_product
[
  (sku_id:TEXT, PK, ex:[AW-MN-001, DN-LT-010, NT-LT-001])
  (brand_family:TEXT, ex:[ArcWave, Dawn, FahMai])
  (dept_code:TEXT, ex:[SF])
  (category:TEXT, ex:[smartwatch, laptop, monitor])
  (subcategory:TEXT, ex:[flagship, midrange])
  (msrp_thb:NUMERIC(18,2), ex:[6900.00, 4900.00, 29900.00])
  (msrp_tier:TEXT, ex:[>=30K, <10K, 10K-30K])
  (is_third_party:BOOL, ex:[False, True])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-001, V-002])
  (launch_date:DATE, ex:[2023-01-01, 2024-01-01, 2025-07-15])
  (end_of_life_date:DATE)
  (warranty_months:INT, ex:[12, 36, 24])
  (care_plus_eligible:BOOL, ex:[False, True])
]

# Table: dim_customer
[
  (customer_id:TEXT, PK, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000003])
  (first_name_th:TEXT, ex:[นริศ, เกษม, ขวัญใจ])
  (last_name_th:TEXT, ex:[มหาเปียร, ศรีวรรณ, วรากร])
  (first_name_en:TEXT, ex:[B2B Customer 013600, B2B Customer 013400, B2B Customer 028800])
  (last_name_en:TEXT, ex:[Srisawat, Phiphat, Chanphen])
  (email:TEXT, ex:[customer029805@example.test, customer007268@example.test, customer018231@example.test])
  (phone:TEXT, ex:[0800003722, 0800019551, 0800011261])
  (province:TEXT, ex:[Bangkok])
  (region:TEXT, ex:[BKK])
  (age:INT, ex:[64, 62, 55])
  (gender:TEXT, ex:[M, F])
  (signup_date:DATE, ex:[2024-02-01, 2024-01-05])
  (customer_type:TEXT, ex:[B2C, B2B])
  (b2b_subtype:TEXT, ex:[Enterprise, SME])
  (account_manager_id:TEXT, ex:[EMP-L3-00002])
  (payment_terms:TEXT, ex:[NET-30, NET-60])
  (loyalty_tier:TEXT, ex:[gold, none, platinum])
  (channel_pref:TEXT, ex:[offline, mixed])
  (uses_line_oa:BOOL, ex:[False, True])
]

# Table: dim_employee
[
  (employee_id:TEXT, PK, ex:[EMP-L3-00001, EMP-L3-00002, EMP-L3-00003])
  (first_name_th:TEXT, ex:[Staff037, Staff330, Staff149])
  (last_name_th:TEXT, ex:[Approver, Lead, Chairman])
  (first_name_en:TEXT, ex:[Staff037, Staff330, Staff149])
  (last_name_en:TEXT, ex:[Approver, Lead, Chairman])
  (email:TEXT, ex:[staff518.m@fahmai.co.th, staff207.m@fahmai.co.th, vichai.l@fahmai.co.th])
  (phone:TEXT)
  (branch_code:TEXT, ex:[BKK-R9])
  (dept_code:TEXT, ex:[B2B, CEO, FIN])
  (section:TEXT)
  (unit:TEXT)
  (position_title:TEXT)
  (position_level:TEXT, ex:[C-level, Director, IC])
  (reports_to_employee_id:TEXT, ex:[EMP-L3-00001, EMP-L3-00002, EMP-L3-00003])
  (hire_date:DATE, ex:[2023-01-01])
  (termination_date:DATE)
  (termination_reason:TEXT)
  (status:TEXT, ex:[active])
  (employment_type:TEXT, ex:[FT])
  (is_canon_leader:BOOL, ex:[False, True])
  (canon_role_label:TEXT, ex:[Board Chair, Founder & CEO, Incoming CEO])
]

# Table: dim_branch
[
  (branch_code:TEXT, PK, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (name_th:TEXT, ex:[FahMai Phuket Road, FahMai Chiang Mai Maya, FahMai Pattaya Central])
  (name_en:TEXT, ex:[FahMai Phuket Road, FahMai Chiang Mai Maya, FahMai Pattaya Central])
  (branch_type:TEXT, ex:[branch, remote, hq])
  (is_service_center:BOOL, ex:[False, True])
  (retail_floor_coefficient:NUMERIC(18,6), ex:[1.200000, 0.900000, 0.000000])
  (traffic_share_pct:NUMERIC(18,6), ex:[0.090000, 0.070000, 0.060000])
  (employee_headcount_share_pct:NUMERIC(18,6), ex:[0.080000, 0.050000, 0.070000])
]

# Table: dim_vendor
[
  (vendor_id:TEXT, PK, ex:[V-001, V-006, V-013])
  (name_th:TEXT, ex:[PayWise, NorthernShip, LegacyShip])
  (name_en:TEXT, ex:[PayWise, NorthernShip, LegacyShip])
  (category:TEXT, ex:[consumer_brand, payments, logistics])
  (role:TEXT, ex:[warranty_partner, partner_brand, processor])
  (payment_terms:TEXT, ex:[NET-15, NET-30])
  (invoice_cadence:TEXT, ex:[monthly, weekly])
  (is_partner_brand:BOOL, ex:[False, True])
  (is_component_supplier:BOOL, ex:[False])
  (start_date:DATE, ex:[2023-01-01, 2025-04-01])
  (end_date:DATE, ex:[2025-03-31])
]

# Table: dim_date  (fiscal_year is BUDDHIST ERA; use fiscal_year_ce for CE)
[
  (date_iso:DATE, PK, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (date_be_string:TEXT, ex:[2568-04-11, 2568-01-04, 2568-03-02])
  (day_of_week:INT, ex:[7, 1, 5])
  (is_thai_public_holiday:BOOL, ex:[False])
  (holiday_name:TEXT)
  (fiscal_year:INT, ex:[2568, 2567])
  (fiscal_quarter:INT, ex:[1, 3, 4])
]

# Table: dim_policy_version  (as-of: effective_date<=D AND (end_date IS NULL OR end_date>D))
[
  (policy_version_id:TEXT, PK, ex:[1, 10, 11])
  (policy_class:TEXT, ex:[signing_authority, shipping, membership])
  (policy_variable:TEXT, ex:[return_window_days, point_earning_rate_per_thb, refund_threshold_thb])
  (scope_filter:TEXT, ex:[global])
  (value_numeric:NUMERIC(18,4), ex:[2000.0000, 5000.0000, 14.0000])
  (value_text:TEXT, ex:[novatech_service])
  (policy_value_table_ref:TEXT, ex:[dim_care_plus_sku_tier, dim_signing_authority_ladder])
  (effective_date:DATE, ex:[2025-03-15, 2025-04-01, 2025-02-15])
  (end_date:DATE, ex:[2025-03-01, 2025-03-15, 2025-04-01])
  (policy_doc_filename:TEXT)
]

# Table: dim_signing_authority_ladder
[
  (ladder_row_id:TEXT, PK, ex:[2, 7, 1])
  (policy_version_id:TEXT, -> dim_policy_version.policy_version_id, ex:[6, 5])
  (position_level_code:TEXT, ex:[Director, C-level, Manager])
  (dept_code:TEXT, ex:[SUP])
  (amount_ceiling_thb:NUMERIC(18,2), ex:[5000000.00, 5000.00, 100000.00])
  (min_co_signers:INT, ex:[0, 1])
  (co_signer_min_position_level_code:TEXT, ex:[Manager])
  (description_th:TEXT)
]

# Table: dim_vendor_contract_version
[
  (contract_version_id:TEXT, PK, ex:[1, 10, 11])
  (vendor_id:TEXT, ex:[V-001, V-006, V-013])
  (version_number:INT, ex:[1, 3, 4])
  (effective_date:DATE, ex:[2024-09-01, 2024-07-01, 2025-12-01])
  (end_date:DATE, ex:[2025-09-01, 2025-11-01, 2025-10-01])
  (contract_pdf_filename:TEXT, ex:[contracts/V-006-v1.pdf, contracts/V-001-v4.pdf, contracts/V-014-v3.pdf])
  (amendment_summary:TEXT)
]

# Table: dim_promo_campaign
[
  (campaign_id:TEXT, PK, ex:[CLEAR-EOY-2568, MEGA-1212-2568, MEGA-1212-2567])
  (start_timestamp:TIMESTAMP, ex:[2025-12-19 17:00:00+00:00, 2025-11-09 17:00:00+00:00, 2025-12-10 17:00:00+00:00])
  (end_timestamp:TIMESTAMP, ex:[2025-12-13 16:59:59+00:00, 2025-11-12 16:59:59+00:00, 2024-12-13 16:59:59+00:00])
  (scope_filter:TEXT, ex:[sku-list:[DN-LT-010,WK-SW-004,AW-MN-001], sku-list:[SF-Galaxy-Pro-2568], all])
  (description_th:TEXT)
  (description_en:TEXT)
]

# Table: dim_promo_mechanic
[
  (promo_mechanic_id:TEXT, PK, ex:[1, 4, 8])
  (campaign_id:TEXT, -> dim_promo_campaign.campaign_id, ex:[CLEAR-EOY-2568, MEGA-1212-2568, MEGA-1212-2567])
  (discount_type:TEXT, ex:[point_multiplier, pct_off])
  (discount_value:NUMERIC(18,4), ex:[0.1200, 0.0500, 0.3000])
  (point_multiplier:NUMERIC(18,4), ex:[2.0000])
  (min_basket_thb:NUMERIC(18,2))
  (description_th:TEXT)
]

# Table: dim_product_recall_history
[
  (history_id:TEXT, PK, ex:[2, 3, 1])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[NT-LT-001])
  (status:TEXT, ex:[normal, active, completed])
  (transition_date:DATE, ex:[2025-10-15, 2025-09-10, 2024-01-01])
]

# Table: dim_bank_account
[
  (account_id:TEXT, PK, ex:[BBL-OPER, KBANK-OPER, OPER-BKK-CTW])
  (bank:TEXT, ex:[BBL, SCB, KBank])
  (account_number:TEXT, ex:[100-1-10000-1, 003-1-00001-3, 108-3-10008-9])
  (account_role:TEXT, ex:[operating])
  (associated_branch_code:TEXT, ex:[BKK-PKT, KKC-CTRL, CNX-MAYA])
  (currency:TEXT, ex:[THB])
  (opening_balance_thb:NUMERIC(18,2), ex:[1000000.00, 3000000.00, 10000000.00])
  (statement_cadence:TEXT, ex:[monthly])
]

# Table: dim_department
[
  (dept_code:TEXT, PK, ex:[CEO, HR, RET])
  (dept_name_th:TEXT, ex:[Operations, Finance, Retail])
  (dept_name_en:TEXT, ex:[Operations, Finance, Retail])
  (dept_type:TEXT, ex:[corporate, product_division])
]

# Table: dim_position_level
[
  (position_level_code:TEXT, PK, ex:[Director, C-level, Manager])
  (rank:INT, ex:[6, 1, 3])
  (default_signing_authority_thb:NUMERIC(18,2), ex:[5000000.00, 100000.00, 1000000.00])
]

# Table: dim_care_plus_sku_tier
[
  (tier_row_id:TEXT, ex:[1, 2])
  (policy_version_id:TEXT, ex:[7])
  (sku_id:TEXT, ex:[NT-LT-001, SF-Galaxy-Pro-2568])
  (sku_category:TEXT)
  (care_plus_price_thb:NUMERIC(18,2), ex:[3490.00, 3990.00])
  (coverage_months:INT, ex:[24, 36])
  (description_th:TEXT)
]

【Foreign keys】
sales_order_360.customer_id = dim_customer.customer_id
sales_order_360.branch_code = dim_branch.branch_code
sales_order_360.employee_id = dim_employee.employee_id
sales_order_360.promo_campaign_id = dim_promo_campaign.campaign_id
sales_line_360.txn_id = sales_order_360.txn_id
sales_line_360.sku_id = dim_product.sku_id
sales_line_360.vendor_id = dim_vendor.vendor_id
finance_event.vendor_id = dim_vendor.vendor_id
finance_event.employee_id = dim_employee.employee_id
finance_event.approver_employee_id = dim_employee.employee_id
finance_event.account_id = dim_bank_account.account_id
customer_ops_event.customer_id = dim_customer.customer_id
customer_ops_event.txn_id = sales_order_360.txn_id
customer_ops_event.sku_id = dim_product.sku_id
customer_ops_event.campaign_id = dim_promo_campaign.campaign_id
inventory_event.sku_id = dim_product.sku_id
inventory_event.branch_code = dim_branch.branch_code
product_catalog.vendor_id = dim_vendor.vendor_id
dim_product.vendor_id = dim_vendor.vendor_id
dim_signing_authority_ladder.policy_version_id = dim_policy_version.policy_version_id
dim_promo_mechanic.campaign_id = dim_promo_campaign.campaign_id
dim_product_recall_history.sku_id = dim_product.sku_id

## Raw fact_* tables (fah_sai_lpk_core — no M-Schema block):
fact_sales, fact_sales_line_item, fact_return, fact_refund_paid, fact_warranty_claim,
fact_promo_redemption, fact_inventory_movement, fact_inventory_monthly_snapshot,
fact_loyalty_ledger, fact_payroll, fact_cs_interaction, fact_shipping,
fact_bank_transaction, fact_vendor_payment
(Use only when a question names FACT_* explicitly or for data-quality checks.)

'''
